kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: import-demo-kafka-0
  labels:
    app: demo-kafka
    volume.beta.kubernetes.io/storage-class: local-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: local-storage 
